### PR TITLE
[clang-tidy] add check for capturing lambda coroutines

### PR DESCRIPTION
**Pull request by BenPope**
Signed-off-by: Noah Watkins <noahwatkins@gmail.com>
(cherry picked from commit 5725e80378fe5f34a197502970fc347f3b451215)

### CODE REVIEW

**Review by dotnwat — APPROVED** [review]
lgtm. did you run the unit tests?

**Comment by BenPope** [comment]
> lgtm. did you run the unit tests?

No. And they didn't work. I've shuffled some files around in my [force-pushes](https://github.com/redpanda-data/llvm-project/compare/6af314de41c2bbd162e1892e5c584220163b7b5a..997151b480b09d915fdef0ce40ed4f4e470074c3)

**Comment by dotnwat** [comment]
> No. And they didn't work. I've shuffled some files around in my [force-pushes](https://github.com/redpanda-data/llvm-project/compare/6af314de41c2bbd162e1892e5c584220163b7b5a..997151b480b09d915fdef0ce40ed4f4e470074c3)

I'm not really sure what this means. Are you saying that the unit tests for the coroutine capture check failed?

**Comment by BenPope** [comment]
> > No. And they didn't work. I've shuffled some files around in my [force-pushes](https://github.com/redpanda-data/llvm-project/compare/6af314de41c2bbd162e1892e5c584220163b7b5a..997151b480b09d915fdef0ce40ed4f4e470074c3)
> 
> I'm not really sure what this means. Are you saying that the unit tests for the coroutine capture check failed?

Yeah, it failed to compile because files have moved around, specifically the `Inputs/coroutines.h`.

They pass now.

**Review by dotnwat — APPROVED** [review]

**Pull request merged**
